# Write a Python program to create a tensor of shape (3, 3) filled with random numbers between 0 and 1

In [ ]:
import tensorflow as tf

In [ ]:
tensor=tf.random.uniform(shape=(3,3),minval=0,maxval=1)

In [ ]:
print("Random Tensor:")
print(tensor)

Random Tensor:
tf.Tensor(
[[0.8148534  0.2639855  0.47563052]
 [0.5754212  0.9672632  0.49600196]
 [0.27123153 0.8032583  0.56329334]], shape=(3, 3), dtype=float32)


# Perform basic tensor operations including matrix addition, multiplication, and transpose.

In [ ]:
A = tf.random.uniform((3, 3), minval=0, maxval=1)
B = tf.random.uniform((3, 3), minval=0, maxval=1)

In [ ]:
print("Tensor A:",A)
print("Tensor B:",B)

Tensor A: tf.Tensor(
[[0.36798    0.5380745  0.11884356]
 [0.9194875  0.6565393  0.4056394 ]
 [0.2587042  0.72560775 0.9852005 ]], shape=(3, 3), dtype=float32)
Tensor B: tf.Tensor(
[[0.00746524 0.06889498 0.13134813]
 [0.0886302  0.4170078  0.7812102 ]
 [0.25929928 0.70421004 0.7636162 ]], shape=(3, 3), dtype=float32)


In [ ]:
# Matrix Addition
add_result = tf.add(A, B)
print("Matrix Addition (A + B):")
print(add_result)

Matrix Addition (A + B):
tf.Tensor(
[[0.37544525 0.6069695  0.2501917 ]
 [1.0081177  1.0735471  1.1868496 ]
 [0.51800346 1.4298178  1.7488167 ]], shape=(3, 3), dtype=float32)


In [ ]:
# Multiplication
mul_result = tf.matmul(A, B)
print("Matrix Multiplication (A x B):")
print(mul_result)

Matrix Multiplication (A x B):
tf.Tensor(
[[0.08125275 0.33342406 0.55943364]
 [0.17023541 0.6227854  0.943421  ]
 [0.32170382 1.0141956  1.3531475 ]], shape=(3, 3), dtype=float32)


In [ ]:
# Transpose
transpose_A = tf.transpose(A)
print("Transpose of Tensor A:")
print(transpose_A)

Transpose of Tensor A:
tf.Tensor(
[[0.36798    0.9194875  0.2587042 ]
 [0.5380745  0.6565393  0.72560775]
 [0.11884356 0.4056394  0.9852005 ]], shape=(3, 3), dtype=float32)


# Convert the resulting tensor into a NumPy array and then reshape it into a (1, 9) tensor.

In [ ]:
tensor=tf.random.uniform(shape=(3,3),minval=0,maxval=1)
print("Original Tensor:",tensor)

Original Tensor: tf.Tensor(
[[0.478948   0.1920855  0.08778834]
 [0.4376706  0.36405396 0.8761258 ]
 [0.24626207 0.675336   0.09535336]], shape=(3, 3), dtype=float32)


In [ ]:
numpy_array=tensor.numpy()
print("Converted Numpy array:",numpy_array)

Converted Numpy array: [[0.478948   0.1920855  0.08778834]
 [0.4376706  0.36405396 0.8761258 ]
 [0.24626207 0.675336   0.09535336]]


In [ ]:
reshaped_tensor=tf.reshape(tensor,(1,9))
print("Reshaped Tensor:",reshaped_tensor)

Reshaped Tensor: tf.Tensor(
[[0.478948   0.1920855  0.08778834 0.4376706  0.36405396 0.8761258
  0.24626207 0.675336   0.09535336]], shape=(1, 9), dtype=float32)
