In [ ]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
tf.__version__

'2.19.0'

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
x=tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
y=tf.constant(10.6)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.600000381469727>

In [ ]:
s=tf.constant('India')
s

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [ ]:
l=tf.constant([1,2,3,4,5,6,7])
l

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [ ]:
import numpy as np
l_2d=np.array([[1,2,3],[4,5,6]])
l=tf.constant(l_2d)
l

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
t_2d=tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_1d=tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
t_3d=tf.constant([[[1,2,3],[4,5,6]]])
t_3d

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
# for customizing
t_2d=tf.constant([1,2,3,4],shape=(2,2),dtype='int32')
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_3d_1=tf.constant([[[1,2],[3,4],[5,6]]],dtype='float32')
t_3d_1


<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float32)>

In [ ]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
t_3d_1.shape

TensorShape([1, 3, 2])

# TensorFlow **Variable**

In [ ]:
import tensorflow as tf
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.name

'Variable:0'

In [ ]:
x.shape

TensorShape([4])

In [ ]:
y=tf.Variable([1.0,2.0,3.0])
y

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
z=tf.Variable(True,False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [ ]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# Create TensorFlow Variable with different shape

In [ ]:
t_2d=tf.Variable([[1,2],[3,4]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Get the index of highest value

In [ ]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Change/Assign new value to tensor

In [ ]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.assign([4,5,6,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 8], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 8], dtype=int32)>

In [ ]:
#Assign varialbe with another memory

In [ ]:
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 11,  8, 16], dtype=int32)>

Tensorflow Math modules

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
a=10
b=20

In [ ]:
a+b

30

In [ ]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
# Addition of 2 values
l1=[1,2,3,4]
l2=[6,7,8,9]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [ ]:
# Addition of 2 tuples

In [ ]:
t1=(1,2,3,4)
t2=(6,7,7,9)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 10, 13], dtype=int32)>

In [ ]:
# Given a tensor x and y,power x^y

In [ ]:
x=tf.constant([[2,3],[3,3]])
y=tf.constant([[2,3],[3,4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 27],
       [27, 81]], dtype=int32)>

In [ ]:
# tf.maths.abs
x=tf.constant([-2,3.4,3,25])
tf.abs(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2. ,  3.4,  3. , 25. ], dtype=float32)>

In [ ]:
#complex number
x=tf.constant([[-2.25+4.75],[-3.25+4.5]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.5 ],
       [1.25]], dtype=float32)>

In [ ]:
#tf.maths.subtract
x=[1,2,3,4]
y=1
tf.subtract(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [ ]:
# tf.maths.multiply
import tensorflow as tf
x=tf.constant(([1,2,3,4]))
tf.math.multiply(x,x)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
tf.math.multiply(7,6)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
x=tf.ones([1,2])
y=tf.zeros([2,1])
x*y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
# tf.math.maximum

x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-2.,0.,2.,5.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [ ]:
x=tf.constant([-5.,0.,0.,0.])
y=tf.constant([-2.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-2.,  0.,  0.,  0.], dtype=float32)>

In [ ]:
# tf.math.minimum

x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-2.,0.,2.,5.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-2.,  0.,  0.,  0.], dtype=float32)>

In [ ]:
x=tf.constant([-5.,0.,0.,0.])
y=tf.constant([-2.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2., -2., -2.], dtype=float32)>

In [ ]:
# tf.math.log
x=tf.constant([0,0.5,1,5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [ ]:
# tf.math.divide
x=tf.constant([16,12,11])
y=tf.constant([4,6,2])
tf.math.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [ ]:
# tf.math.pow
x=tf.constant([[2,2],[3,3]])
y=tf.constant([[3,3],[2,2]])
tf.math.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 8],
       [9, 9]], dtype=int32)>

In [ ]:
# tf.math.sqrt
x=tf.constant([[4.0],[16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [ ]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [ ]:
tf.ones((1)),tf.float32


(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [ ]:
ones_2d=tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [ ]:
ones_3d=tf.ones((2,2,4)),tf.float32
ones_3d

(<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=float32)>,
 tf.float32)

PlaceHolder is a variable that we will assign data to at a later date

In [ ]:
tf.placeholder(dtype.float32,shape=(400,400))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [ ]:
tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [ ]:
tf.compat.v1.disable_eager_execution()

In [ ]:
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [ ]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [ ]:
c=tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [ ]:
import numpy as np

In [ ]:
ones_array=np.ones((400,400),np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [ ]:
with tf.compat.v1.Session() as sess:
  d=sess.run(c,feed_dict={a:ones_array,b:ones_array})

In [ ]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)